---
- name: Demo jinja2 templates
  hosts: dbservers
  vars:
    anonymous_enable: yes
    local_enable: yes
    write_enable: yes
    anon_upload_enable: yes
  tasks:
    - name: Install vsftpd
      yum:
        name: vsftpd
        state: present

    - name: use jinja2 template in creating vsftpd config
      template:
        src: vsftpd.j2
        dest: /etc/vsftpd/vsftpd.conf
