---
- name: copy localfacts
  hosts: all
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: bright.fact
  tasks:
    - name : create facts directory
      file: 
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: Install new facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
...
