---
- name: example of using vars-1
  hosts: all
  vars:
    dellatech: james44
  vars_files:
    - vars/uservar1
  tasks:
    - name: delete user {{ dellatech }}
      user:
        name: "{{ dellatech }}"
        state: absent
    
    - name: create user {{ user }}
      user: 
        name: "{{ user }}"
        state: present
