---
- name: complex when
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Demo when
      dnf:
        name: nginx
        state: latest
      when: >
        ( ansible_distribution == "RedHat" and ansible_memfree_mb > 25 )
        or
        ( ansible_distribution == "CentOS" and ansible_memfree_mb > 1024 )
