---
- name: demo multiple conditions
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: absent
      when:
        - ansible_distribution == "RedHat"
        - ansible_memfree_mb > 20

