---
- name: Demo blocks
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks: 
    - name: setting up httpd
      block:
        - name: install httpd
          yum:
            name: httpd
            state: present

        - name: restart httpd
          service:
            name: httpd
            state: restarted 
      when: ansible_distribution == "CentOS"      

