---
- name: customize centos system
  hosts: dbservers
  tasks:
    - name: install desired software package
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' 
      yum:
        state: latest
        name:
          - build-utils
          - dnf-utils
          - net-tools
          - '@Additional Development'
          - '@Networking Tools'
          - '@Standard'
          - '@System Tools'
          - '@Development Tools'

    - name: Remove previous entry from '/etc/hosts'
      lineinfile: 
        dest: '/etc/hosts'
        regexp: "{{ hostvars[item].ansible_default_ipv4.address }}"
        state: absent
        backup: yes
      when: hostvars[item].ansible_default_ipv4.address is defined
      loop: "{{ groups['all] }}"

    - name: write own IP, FQDN and short hostname into '/etc/hosts'
      lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}" 
      state: present
      when: hostvars[item].ansible_default_ipv4.address is defined         
      loop: "{{ groups['all'] }}"
