---
- name: more exx
  hosts: all
  tasks:
    - name: get crond service status
      command: /usr/bin/systemcl is-active crond
      ignore_errors: yes
      register: result

    - name: restart sshd based on crond status
      service:
        name: sshd
        state: restarted
      when: result.rc == 0  
