---
- name: install apache
  hosts: webservers
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
    - name: copy content of index.html
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
    - name: start httpd and enable
      service:
        name: httpd
        state: started
        enabled: true
...


   
